version: 2

sources:
  - name: staging
    database: dtc-de-123
    schema: dezoomcamp

    tables:
      -  name: external_green_tripdata
      -  name: external_yellow_tripdata
      -  name: external_fhv_tripdata